<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-R5GDS62" name="dao.LoaiNhaCCDAONGTest" tests="5" failures="2" timestamp="18 Jun 2020 08:39:07 GMT" time="2.249" errors="0">
  <testcase name="test_Delete" time="0.812" classname="dao.LoaiNhaCCDAONGTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.NullPointerException but got org.testng.TestException: 
Expected exception java.lang.NullPointerException but got java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint &quot;FK_NhaCungCap_LoaiNhaCC&quot;. The conflict occurred in database &quot;DA1_QLKho&quot;, table &quot;dbo.NhaCungCap&quot;, column &#039;MaLoaiCC&#039;.">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.NullPointerException but got org.testng.TestException: 
Expected exception java.lang.NullPointerException but got java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_NhaCungCap_LoaiNhaCC". The conflict occurred in database "DA1_QLKho", table "dbo.NhaCungCap", column 'MaLoaiCC'.
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1245)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: org.testng.TestException: 
Expected exception java.lang.NullPointerException but got java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_NhaCungCap_LoaiNhaCC". The conflict occurred in database "DA1_QLKho", table "dbo.NhaCungCap", column 'MaLoaiCC'.
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	... 15 more
Caused by: java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_NhaCungCap_LoaiNhaCC". The conflict occurred in database "DA1_QLKho", table "dbo.NhaCungCap", column 'MaLoaiCC'.
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:53)
	at dao.LoaiNhaCCDAO.delete(LoaiNhaCCDAO.java:31)
	at dao.LoaiNhaCCDAONGTest.test_Delete(LoaiNhaCCDAONGTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	... 17 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_NhaCungCap_LoaiNhaCC". The conflict occurred in database "DA1_QLKho", table "dbo.NhaCungCap", column 'MaLoaiCC'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:328)
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:47)
	... 25 more
]]>
    </failure>
  </testcase> <!-- test_Delete -->
  <testcase name="test_Insert" time="0.047" classname="dao.LoaiNhaCCDAONGTest">
    <failure type="java.lang.RuntimeException" message="com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint &#039;PK_LoaiNhaCC&#039;. Cannot insert duplicate key in object &#039;dbo.LoaiNhaCC&#039;. The duplicate key value is (MLCC02).">
      <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_LoaiNhaCC'. Cannot insert duplicate key in object 'dbo.LoaiNhaCC'. The duplicate key value is (MLCC02).
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:53)
	at dao.LoaiNhaCCDAO.insert(LoaiNhaCCDAO.java:23)
	at dao.LoaiNhaCCDAONGTest.test_Insert(LoaiNhaCCDAONGTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_LoaiNhaCC'. Cannot insert duplicate key in object 'dbo.LoaiNhaCC'. The duplicate key value is (MLCC02).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:328)
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:47)
	... 25 more
]]>
    </failure>
  </testcase> <!-- test_Insert -->
  <testcase name="test_Exists" time="0.218" classname="dao.LoaiNhaCCDAONGTest"/>
  <testcase name="test_Update" time="0.531" classname="dao.LoaiNhaCCDAONGTest"/>
  <testcase name="testSelect" time="0.641" classname="dao.LoaiNhaCCDAONGTest"/>
</testsuite> <!-- dao.LoaiNhaCCDAONGTest -->
